default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: maxwell
  password: post1234

development:
  <<: *default
  database: recipe_app_development1

test:
  <<: *default
  database: recipe_app_test1


production:
  <<: *default
  database: recipe_app_production
  username: recipe_app
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
